# Generated by Django 4.2.20 on 2025-03-15 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('completed', '已完成'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='狀態')),
                ('categories', models.CharField(max_length=255, verbose_name='爬取類別')),
                ('limit_per_category', models.IntegerField(default=5, verbose_name='每類別文章數')),
                ('use_threading', models.BooleanField(default=False, verbose_name='使用多線程')),
                ('max_workers', models.IntegerField(default=4, verbose_name='最大線程數')),
                ('result_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='結果檔案路徑')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '爬蟲任務',
                'verbose_name_plural': '爬蟲任務',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='關鍵詞')),
                ('pos', models.CharField(max_length=10, verbose_name='詞性')),
                ('frequency', models.IntegerField(verbose_name='頻率')),
                ('category', models.CharField(max_length=50, verbose_name='類別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='scraper.scrapejob', verbose_name='爬蟲任務')),
            ],
            options={
                'verbose_name': '關鍵詞分析',
                'verbose_name_plural': '關鍵詞分析',
                'ordering': ['-frequency'],
                'indexes': [models.Index(fields=['job', 'category'], name='scraper_key_job_id_9d0572_idx'), models.Index(fields=['job', 'frequency'], name='scraper_key_job_id_03e3e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100, verbose_name='文章ID')),
                ('category', models.CharField(max_length=50, verbose_name='類別')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('date', models.DateTimeField(verbose_name='發布日期')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('link', models.URLField(verbose_name='原始連結')),
                ('photo_links', models.TextField(blank=True, null=True, verbose_name='圖片連結')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='scraper.scrapejob', verbose_name='爬蟲任務')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-date'],
                'unique_together': {('job', 'item_id')},
            },
        ),
    ]
