# Generated by Django 4.2.20 on 2025-03-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100, verbose_name='實體')),
                ('entity_type', models.CharField(max_length=20, verbose_name='實體類型')),
                ('frequency', models.IntegerField(verbose_name='頻率')),
                ('category', models.CharField(max_length=50, verbose_name='類別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='named_entities', to='scraper.scrapejob', verbose_name='爬蟲任務')),
            ],
            options={
                'verbose_name': '命名實體分析',
                'verbose_name_plural': '命名實體分析',
                'ordering': ['-frequency'],
                'indexes': [models.Index(fields=['job', 'category'], name='scraper_nam_job_id_8e8726_idx'), models.Index(fields=['job', 'entity_type'], name='scraper_nam_job_id_ab5e03_idx'), models.Index(fields=['job', 'frequency'], name='scraper_nam_job_id_583fe5_idx')],
            },
        ),
    ]
